name: Checks
on:
  push:
    paths:
      - templates/*
      - python/*
      - .github/workflows/*
      - style.css
      - resume.yaml
jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: HatsuneMiku3939/direnv-action@v1
      - run: just format-check
  Rendering:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: HatsuneMiku3939/direnv-action@v1
      - run: just poetry-install
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: just render
      - run: just check-for-changes
