name: Checks
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: HatsuneMiku3939/direnv-action@v1
      - run: just format-check
  Rendering:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: HatsuneMiku3939/direnv-action@v1
      - run: just poetry-install
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: just render
      - run: just check-for-changes
