name: Render templates
on:
  push:
    paths:
      - templates/*
      - python/*
      - .github/workflows/*
      - style.css
      - resume.yaml
jobs:
  Render-Templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: HatsuneMiku3939/direnv-action@v1

      - run: just poetry-install
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - run: just render

      - name: Commit if changed
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Sean Gatewood'
            git config --global user.email 'sgatewood@users.noreply.github.com'
            git add .
            git commit -am "CI: Auto-render templates"
            if [[ $(git branch --show-current) == "main" ]]; then
              git checkout -b ci-auto-render-templates
              git push origin ci-auto-render-templates
              gh pr create --base main --fill
              gh pr merge --merge --auto --delete-branch
            else
              echo "Looks good"
            fi
          else
            echo "No changes :-)"
          fi
