name: Render templates
on:
  push:
    paths:
      - templates/*
      - python/*
      - .github/workflows/*
      - style.css
      - resume.yaml
jobs:
  Render-Templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install wkthtmltopdf
        run: |
          sudo apt-get install -y xfonts-base xfonts-75dpi
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb

      - run: poetry install --no-interaction --no-root
        working-directory: python
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - run: poetry run python3 render_templates.py
        working-directory: python

      - name: Commit if changed
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Sean Gatewood'
            git config --global user.email 'sgatewood@users.noreply.github.com'
            git add .
            git commit -am "CI: Auto-render templates"
            if [[ $(git branch --show-current) == "main" ]]; then
              git checkout -b ci-auto-render-templates
              git push origin ci-auto-render-templates
              gh pr create --base main --fill
              gh pr merge --merge --auto --delete-branch
            else
              echo "Looks good"
              git push
            fi
          else
            echo "No changes :-)"
          fi
